const mockLeaderboard = [
  {
    name: 'Corinthians',
    totalPoints: 9,
    totalGames: 3,
    totalVictories: 3,
    totalDraws: 0,
    totalLosses: 0,
    goalsFavor: 7,
    goalsOwn: 1,
    goalsBalance: 6,
    efficiency: '100.00'
  },
  {
    name: 'Palmeiras',
    totalPoints: 7,
    totalGames: 3,
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 9,
    goalsOwn: 4,
    goalsBalance: 5,
    efficiency: '77.78'
  },
  {
    name: 'Ferroviária',
    totalPoints: 7,
    totalGames: 4,
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 6,
    goalsOwn: 4,
    goalsBalance: 2,
    efficiency: '58.33'
  },
  {
    name: 'Grêmio',
    totalPoints: 7,
    totalGames: 3,
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 6,
    goalsOwn: 4,
    goalsBalance: 2,
    efficiency: '77.78'
  },
  {
    name: 'Real Brasília',
    totalPoints: 7,
    totalGames: 4,
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 4,
    goalsOwn: 4,
    goalsBalance: 0,
    efficiency: '58.33'
  },
  {
    totalPoints: 7,
    totalGames: 4,
    totalVictories: 2,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 4,
    goalsOwn: 4,
    goalsBalance: 0,
    efficiency: '58.33'
  },
  {
    name: 'Bahia',
    totalPoints: 4,
    totalGames: 4,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 6,
    goalsOwn: 5,
    goalsBalance: 1,
    efficiency: '33.33'
  },
  {
    name: 'Santos',
    totalPoints: 4,
    totalGames: 2,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 4,
    goalsOwn: 3,
    goalsBalance: 1,
    efficiency: '66.67'
  },
  {
    name: 'São Paulo',
    totalPoints: 4,
    totalGames: 3,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 5,
    goalsOwn: 5,
    goalsBalance: 0,
    efficiency: '44.44'
  },
  {
    name: 'São José-SP',
    totalPoints: 3,
    totalGames: 3,
    totalVictories: 1,
    totalDraws: 0,
    totalLosses: 2,
    goalsFavor: 3,
    goalsOwn: 4,
    goalsBalance: -1,
    efficiency: '33.33'
  },
  {
    name: 'Avaí/Kindermann',
    totalPoints: 3,
    totalGames: 4,
    totalVictories: 1,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 7,
    goalsBalance: -4,
    efficiency: '25.00'
  },
  {
    name: 'Minas Brasília',
    totalPoints: 2,
    totalGames: 3,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 3,
    goalsOwn: 4,
    goalsBalance: -1,
    efficiency: '22.22'
  },
  {
    name: 'Flamengo',
    totalPoints: 2,
    totalGames: 3,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 1,
    goalsOwn: 2,
    goalsBalance: -1,
    efficiency: '22.22'
  },
  {
    name: 'Napoli-SC',
    totalPoints: 2,
    totalGames: 3,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 2,
    goalsOwn: 5,
    goalsBalance: -3,
    efficiency: '22.22'
  },
  {
    name: 'Cruzeiro',
    totalPoints: 1,
    totalGames: 3,
    totalVictories: 0,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 4,
    goalsOwn: 7,
    goalsBalance: -3,
    efficiency: '11.11'
  },
  {
    name: 'Botafogo',
    totalPoints: 0,
    totalGames: 3,
    totalVictories: 0,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 1,
    goalsOwn: 8,
    goalsBalance: -7,
    efficiency: '0.00'
  }
];

export default mockLeaderboard;
